schema: spec-driven
context: >
  Технические требования
  - Component-Driven Development. Максимально готовое решение собрать в Storybook, затем проект.
  - Feature-Driven Architecture.
  - CSS modules. БЭМ. Без лишних библиотек. Предпочтительнее CSS variables. Использовать кастомные стили. clsx.
  - Использовать radix-ui primitives.
  - Иконки в одном компоненте
  - stories хранить рядом с компонентами
  - Compound components
  - Tanstack Table для таблицы.
  - Tanstack Query для запросов.
  - zustand. Испоьзовать immer middleware. slices for auth and table page
  Используемые технологии: Vite, React, React Router, TS, Storybook, Tanstack Query, Tanstack Table, Zustand, React Hook Form, Zod, eslint, prettier
